databases:
  - name: youtubeplayer-27h4
    plan: starter
    databaseName: youtubeplayer
    user: youtubeplayer

services:
  - type: web
    plan: free
    name: youtubeplayer_django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn youtubeplayer.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: youtubeplayer-27h4
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4