# Generated by Django 5.0.7 on 2024-08-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_match', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('home_team', models.CharField(choices=[('Team1', 'Team1'), ('Team2', 'Team2')], max_length=5)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('result', models.CharField(choices=[('Team1', 'Team1'), ('Team2', 'Team2')], max_length=5)),
                ('youtube_link', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MatchClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='youtube.matchdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistClips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=11)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='youtube.matchclip')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='youtube.playlist')),
            ],
        ),
    ]
