# Generated by Django 5.0.7 on 2024-07-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_match', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('home_team', models.CharField(choices=[('Team1', 'Team1'), ('Team2', 'Team2')], max_length=5)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('result', models.CharField(choices=[('Team1', 'Team1'), ('Team2', 'Team2')], max_length=5)),
            ],
        ),
    ]
