# Generated by Django 5.0.7 on 2024-07-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistclips',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_name', to='youtube.matchclip'),
        ),
    ]
