# Generated by Django 5.0.7 on 2024-07-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='youtube_link',
            field=models.CharField(default='youtube_link', max_length=255),
            preserve_default=False,
        ),
    ]
