# Generated by Django 5.0.7 on 2024-07-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_matchdetail_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('clip_name', models.CharField(max_length=100)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='youtube.matchdetail')),
            ],
        ),
    ]
