# Generated by Django 5.0.7 on 2024-07-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_playlistclips_clip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistclips',
            old_name='clip',
            new_name='clip_id',
        ),
    ]
