# Generated by Django 5.0.7 on 2024-07-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_matchclip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.RenameField(
            model_name='matchclip',
            old_name='match_id',
            new_name='match',
        ),
        migrations.CreateModel(
            name='PlaylistClips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='youtube.matchclip')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='youtube.playlist')),
            ],
        ),
    ]
