# Generated by Django 5.0.7 on 2024-07-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_matchclip_match_alter_playlistclips_clip_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchclip',
            name='end_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='matchclip',
            name='start_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
