# Generated by Django 5.0.7 on 2024-07-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_playlist_rename_match_id_matchclip_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_name',
            new_name='name',
        ),
    ]
