# Generated by Django 5.0.7 on 2024-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_matchclip_end_time_alter_matchclip_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistclips',
            name='video_id',
            field=models.CharField(default='KXyEZwolDzE', max_length=11),
            preserve_default=False,
        ),
    ]
