# Generated by Django 5.0.7 on 2024-08-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_playlistclips_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistclips',
            old_name='clip_id',
            new_name='clip',
        ),
    ]
